//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARCA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public producto()
        {
            this.detalle_venta = new HashSet<detalle_venta>();
        }
    
        public int idProducto { get; set; }
        public string codigo { get; set; }
        public string Descripción { get; set; }
        public string medida { get; set; }
        public Nullable<int> stockactual { get; set; }
        public Nullable<int> stockminimo { get; set; }
        public Nullable<System.DateTime> ingreso { get; set; }
        public Nullable<int> precioCosto { get; set; }
        public Nullable<int> precioVenta { get; set; }
        public Nullable<int> precioMayoreo { get; set; }
        public Nullable<int> departamento_id { get; set; }
        public Nullable<int> idproveedor { get; set; }
    
        public virtual departamento departamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_venta> detalle_venta { get; set; }
        public virtual proveedor proveedor { get; set; }
    }
}
