//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARCA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class venta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public venta()
        {
            this.detalle_venta = new HashSet<detalle_venta>();
        }
    
        public int idVenta { get; set; }
        public Nullable<System.DateTime> fecha_venta { get; set; }
        public Nullable<int> total_venta { get; set; }
        public Nullable<int> peso_venta { get; set; }
        public int idusuario { get; set; }
        public int id_tipo_venta { get; set; }
        public int idmetodo { get; set; }
        public Nullable<int> idcliente { get; set; }
    
        public virtual cliente cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_venta> detalle_venta { get; set; }
        public virtual MetodoPago MetodoPago { get; set; }
        public virtual TipoVenta TipoVenta { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
